insert into movie (id, title, url_image, year) values(nextval('movie_seq'), 'Full metal jacket', 'https://pad.mymovies.it/filmclub/2006/04/020/locandina.jpg', 1987);
insert into movie (id, title, url_image, year) values(nextval('movie_seq'), 'Non e'' un paese per vecchi', 'https://aforismi.meglio.it/img/film/Non_%C3%A8_un_paese_per_vecchi.jpg',2007);
insert into movie (id, title, url_image, year) values(nextval('movie_seq'), 'The founder', 'https://pad.mymovies.it/filmclub/2016/03/235/locandina.jpg',2016);
insert into movie (id, title, url_image, year) values(nextval('movie_seq'), 'Harry Potter e la pietra filosofale', 'https://pad.mymovies.it/filmclub/2001/12/001/locandina.jpg',2001);
insert into movie (id, title, url_image, year) values(nextval('movie_seq'), 'Il pianeta delle scimmie', 'https://media-assets.wired.it/photos/615daad62707bc568326abfa/master/w_1600,c_limit/war-for-the-planet-of-the-apes1.jpg',2001);
insert into movie (id, title, url_image, year) values(nextval('movie_seq'), 'Lo chiamavano Jeeg Robot', 'https://www.rai.it/dl/img/2016/02/23/1280x720_1456237082397_jeegrobot.jpg',2015);
insert into movie (id, title, url_image, year) values(nextval('movie_seq'), 'Yesterday', 'https://citynews-today.stgy.ovh/~media/horizontal-mid/20648620006811/yesterday-film-poster-movie-universal-pictures-2.jpg',2019);
insert into artist (id, name, surname, birthdate) values(nextval('artist_seq'), 'Stanley', 'Kubrick', '1927-07-26');
insert into artist (id, name, surname, birthdate) values(nextval('artist_seq'), 'Quentin', 'Tarantino', '1963-03-27');
insert into artist (id, name, surname, birthdate) values(nextval('artist_seq'), 'Federico', 'Fellini', '1920-01-20');
insert into artist (id, name, surname, birthdate) values(nextval('artist_seq'), 'Steven', 'Spielberg', '1946-12-18');
insert into artist (id, name, surname, birthdate) values(nextval('artist_seq'), 'Cristopher', 'Nolan', '1970-07-30');